name: learn_quill_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_markdown: ^0.6.17
  flutter_widget_from_html_core: ^0.10.3
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

assets:
  - assets/sample.json